spring:
  application:
    name: Send Letter Service Container New
  config:
    import: "optional:configtree:/mnt/secrets/rpe-send-letter/"

storage:
  connection: ${STORAGE_ACCOUNT_CONNECTION_STRING}

accesstoken:
  serviceConfig:
    - serviceName: cmc
      newContainerName: new-cmc
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: divorce
      newContainerName: new-divorce
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: finrem
      newContainerName: new-finrem
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: fpl
      newContainerName: new-fpl
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds`
    - serviceName: nfdivorce
      newContainerName: new-nfdivorce
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: probate
      newContainerName: new-probate
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: sscs
      newContainerName: new-sscs
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds



