spring:
  application:
    name: Send Letter Service Container New
  config:
    import: "optional:configtree:/mnt/secrets/rpe-send-letter/"

storage:
  connection: ${STORAGE_ACCOUNT_CONNECTION_STRING}

accesstoken:
  serviceConfig:
    - serviceName: bulkprint
      newContainerName: new
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds