management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  health:
    mail:
      enabled: false

spring:
  application:
    name: Send Letter Service Container New
  config:
    import: "optional:configtree:/mnt/secrets/rpe-send-letter/"
  jackson:
    serialization.write_dates_as_timestamps: false

storage:
  connection: ${STORAGE_ACCOUNT_CONNECTION_STRING}
  leaseTime: ${BLOB_LEASE_TIME:30} #In seconds

accesstoken:
  serviceConfig:
    - serviceName: cmc_claim_store
      containerName: new-cmc
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: divorce_frontend
      containerName: new-divorce
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: finrem_document_generator
      containerName: new-finrem
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: fpl_case_service
      containerName: new-fpl
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds`
    - serviceName: nfdiv_case_api
      containerName: new-nfdivorce
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: probate_backend
      containerName: new-probate
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: sscs
      containerName: new-preview
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: send_letter_tests
      containerName: new-bulkprint
      validity: ${SAS_TOKEN_VALIDITY:300}
    - serviceName: send_letter_backup
      containerName: backup
      validity: ${SAS_TOKEN_VALIDITY:300}
    - serviceName: send_letter_process
      containerName: processed
      validity: ${SAS_TOKEN_VALIDITY:300}


