function:
  image: ${IMAGE_NAME}
  triggers:
    - type: azure-blob
      blobContainerName: "new-bulkprint"
      accountName: "rpesendletter{{ .Values.global.environment }}"
      blobPrefix: manifest-
