function:
  image: 'hmctspublic.azurecr.io/rpe/send-letter-service-container-new::latest'
  envSourceContainerName:"new"
  trigger:
    type: azure-blob
    blob:
      blobContainerName: "new"
      connection: STORAGE_CONNECTION_STRING
