function:
  image: 'hmctspublic.azurecr.io/rpe/send-letter-service-container-new::latest'
  aadIdentityName: send-letter
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 9be248a9-8d37-45e1-a078-11fa981a8393
  keyVaults:
    "rpe-send-letter":
      secrets:
        - name: storage-account-connection-string
          alias: STORAGE_ACCOUNT_CONNECTION_STRING
  trigger:
    type: azure-blob
    blob:
      blobContainerName: "new"