function:
  image: 'hmctspublic.azurecr.io/rpe/send-letter-service-container-new::latest'
  trigger:
    type: azure-blob
    blob:
      blobContainerName: "new"
      connection: STORAGE_CONNECTION_STRING
blobstorage:
  enabled: false
